### ISSUE TITLE
When writing in the terminal the prompt is repeated for each keystroke

### ISSUE THREAD

**Issue by Telsenome** [RobinJ1995/gopro-cloud-media-downloader#1]
First off I want to thank you for creating this script, it's a really neat one!

Here's an example when I try to write the date from when I want to download the files, the prompt is repeated for each keystroke. Is this intentional?

![image](https://user-images.githubusercontent.com/39857933/222734344-94db4af1-a95a-41bc-ab61-6a6e2329235d.png)

**Comment by RobinJ1995** [comment]
The workaround is to make the terminal window big enough to fit the text horizontally, but yes I'm aware of this happening. It's a big in the library I'm using. I can see if switching to a different one fixes this.

**Comment by Telsenome** [comment]
Oh, I see. Will try really re-sizing the window then.

I hope you don’t mind me filing all these issues here in Github by the way, I know this is just a hobby project of yours, but maybe one or two issues could be useful for you. If so, I am happy to have contributed to that! (unfortunately, I am not a programmer and can’t do the programming myself…)

**Comment by RobinJ1995** [comment]
that's fine, happy someone's getting some use out of this. i'm not promising anything but i'll probably fix a couple of these issues when i find the time :)

**Comment by RobinJ1995** [comment]
fixed
