### ISSUE TITLE
How does one close the program without closing the terminal?

### ISSUE THREAD

**Issue by Telsenome** [RobinJ1995/gopro-cloud-media-downloader#2]
I'm sorry for this newbie question but I haven't found out how to close the program without closing the terminal. Is there a key combination I can use to close the program?

OS: Windows 11

**Comment by RobinJ1995** [comment]
Should just be CTRL+C

**Comment by Telsenome** [comment]
Hmm, ctrl-c hasn’t works for me so far. But maybe that’s just a problem with the Windows terminal and not this script itself.

**Comment by RobinJ1995** [comment]
i think this was a side effect of the `prompt-sync` library i was using before. can you check if it's fixed now?

**Comment by Telsenome** [comment]
It works! 🎉
