### ISSUE TITLE
[Feature request] Multi camera support

### ISSUE THREAD

**Issue by Telsenome** [RobinJ1995/gopro-cloud-media-downloader#5]
When using multiple cameras the file names will overlap and currently this script doesn't have support for it, thinking that all files with the same name are the same file instead of different from different cameras. Maybe there could be a way to check the ID or something to determine if the file is actually the same one or if it's a different file from a different camera?

![image](https://user-images.githubusercontent.com/39857933/223669782-ffc1158b-6055-45aa-b69d-19c9f9725f31.png)

![image](https://user-images.githubusercontent.com/39857933/223670152-fa20c2f9-44ae-495c-8629-b685a89a1d00.png)

**Comment by RobinJ1995** [comment]
I've run into this myself too, I'll probably fix this at some point 😅

**Comment by Telsenome** [comment]
Agree… It’s really weird they don’t do something about it!

Do you have any tips on how to mitigate this floor from Gopro side? Using the redownload flag after moving the already downloaded media to another folder maybe?

**Comment by RobinJ1995** [comment]
fixed

**Comment by Telsenome** [comment]
Wow this is wonderful! Thank you so much!
