### ISSUE TITLE
[Bug] After the latest additions there seems to be a dependency issue

### ISSUE THREAD

**Issue by joel-zutobi** [RobinJ1995/gopro-cloud-media-downloader#6]
This is what I get when I try to run the script:

![image](https://user-images.githubusercontent.com/39857933/223985938-3fb3971e-c635-44cc-81e1-3eae5f7c5c1b.png)

**Comment by Telsenome** [comment]
Was able to solve it by running `npm install node-fetch` but I'm not unsure if this is something one should do manually. If so you can close this issue :-)

**Comment by RobinJ1995** [comment]
that's strange as the node-fetch dependency has remained untouched. the only thing i can think of is that you running `npm install` manually might pull in a newer version of it. i'll try updating the dependencies and see if it fixes it.

**Comment by Telsenome** [comment]
Thinking more closely about it I realize I made a mistake, after I cloned the repo from Github I never ran `npm install`

**Comment by Telsenome** [comment]
You can see this mistake in the screenshot I sent as well... Sorry about that!
